// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2oNDNlt8Ket4X5UYNEbqMBSF36tPIJYQ',
    appId: '1:810033168473:web:06c0b7a1a60017280f3148',
    messagingSenderId: '810033168473',
    projectId: 'soluciones-al-instante',
    authDomain: 'soluciones-al-instante.firebaseapp.com',
    storageBucket: 'soluciones-al-instante.appspot.com',
    measurementId: 'G-DFYML0ZLZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQnLii7S9p1ltKQmUjHBx7iEGHF3aofZg',
    appId: '1:810033168473:android:a988344e717e5d320f3148',
    messagingSenderId: '810033168473',
    projectId: 'soluciones-al-instante',
    storageBucket: 'soluciones-al-instante.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8XIUQg6U5M9iw6_hf_wU1-EtcigWOXcA',
    appId: '1:810033168473:ios:4cb333b2c6c6ade80f3148',
    messagingSenderId: '810033168473',
    projectId: 'soluciones-al-instante',
    storageBucket: 'soluciones-al-instante.appspot.com',
    iosBundleId: 'com.example.appAhorro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8XIUQg6U5M9iw6_hf_wU1-EtcigWOXcA',
    appId: '1:810033168473:ios:4cb333b2c6c6ade80f3148',
    messagingSenderId: '810033168473',
    projectId: 'soluciones-al-instante',
    storageBucket: 'soluciones-al-instante.appspot.com',
    iosBundleId: 'com.example.appAhorro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2oNDNlt8Ket4X5UYNEbqMBSF36tPIJYQ',
    appId: '1:810033168473:web:8b068cadc4cb174a0f3148',
    messagingSenderId: '810033168473',
    projectId: 'soluciones-al-instante',
    authDomain: 'soluciones-al-instante.firebaseapp.com',
    storageBucket: 'soluciones-al-instante.appspot.com',
    measurementId: 'G-FEB9W3LBHR',
  );
}
